### ISSUE TITLE
resize throws error after updating file

### ISSUE THREAD

**Issue by Sahara150** [opensheetmusicdisplay/react-opensheetmusicdisplay#5]
So when I first initialized the OSMD component and then changed the url it uses, it updates. 
However, if I resize the window, after the sheet updated, I get an type error (using it in an typescript project, so I added typing to the component), that this.forceUpdate() is not a function.
![forceUpdate_Not_A_Function](https://user-images.githubusercontent.com/74471023/103293742-bdc95880-49f0-11eb-9004-1061d621bf91.png)

My files don´t have titles, so it may have something to do with the title not changing -> no new OSMD setup.

**Comment by sschmidTU** [comment]
This looks like an error within your project, but i think i have a simple solution.
It seems to me that this is due to the code being executed from an anonymous callback function,
and `this` is usually not available in anonymous functions.
You should be able to change your code to give a reference to the object in the resize function:
```typescript
resize(self) {
  self.forceUpdate();
}

// i assume you register the resize event somewhere, change it there:
const self = this;
onResize = () => { resize(self) }; // maybe you can also just use 'this' here and remove the 'const self = this' line
```

**Comment by Sahara150** [comment]
In fact you were right. However I was already able to fix the error, by replacing 

`window.addEventListener('resize', this.resize)` in the OSMD-React-Component with 
`window.addEventListener('resize', () => this.resize())` (and same in the removeEventListener obviously).
