### ISSUE TITLE
How to access the underlying osmd object for advanced configuration

### ISSUE THREAD

**Issue by bastienbeurier** [opensheetmusicdisplay/react-opensheetmusicdisplay#7]
I'm sorry if this is really obvious but I am new to react. I could not find a way to access the underlying osmd object for configuration (e.g. cursor position) based on the react example.

My code is: 

```
import OpenSheetMusicDisplay from './lib/OpenSheetMusicDisplay'
import * as React from 'react';

export function Home() {

    const osmdComponent : React.ReactElement<any, any> = 
        <OpenSheetMusicDisplay 
            file="Fr_Elise.mxl" 
            show="true"/>;

    const osmd = osmdComponent.osmd;

    return(
        <div>
            {osmdComponent}
        </div>
    );
}
```

I logically get the following error `Property 'osmd' does not exist on type 'ReactElement<any, any>'.` on the line `const osmd = osmdComponent.osmd;`.

**Comment by sschmidTU** [comment]
can't you add a getter on OpenSheetMusicDisplay.jsx?
unfortunately i'm not too familiar with React.

**Comment by bneumann** [comment]
Yes @sschmidTU is right:

```
class OpenSheetMusicDisplay extends Component {
    constructor(props) {
      super(props);
      this.state = { dataReady: false };
      this.osmd = undefined; // private field
```

osmd is a private field. I would recommend against the getter though because your Component should wrap the OSMD object and only forward to changes from react. At the time of writing I had no idea that this example project is going to be used that much ;)

Also @mkireva worked on a functional implementation for OSMD using react hooks. That might be a better way to deal with side effects like changing the cursor position or setting the options after rendering.

**Comment by bastienbeurier** [comment]
Thank you @sschmidTU and @bneumann, that answers my question! I'm going to checkout the functional implementation of @mkireva.

**Comment by bastienbeurier** [comment]
@mkireva I couldn't find the functional implementation on your public profile, would you mind pointing me towards it?

**Comment by kair0span** [comment]
@bastienbeurier you can find my implementation on the update-osmd branch.
